### ISSUE TITLE
看了你这个how to use 还是不知道咋弄来着

### ISSUE THREAD

**Issue by zuqiu123** [778477/iOS-LinkMapAnalyzer#2]
看了你这个how to use 还是不知道咋弄来着，可以再细一点吗

**Comment by 778477** [comment]
几个月前更新了项目把编译改为使用makefile进行了。

git clone 项目，进入iOS-LinkMapAnalyzer目录下，进行make编译。即可得到`LinkMapAnalyzer`可执行文件了。
